services:
    # this is our fallback gateway when no mail-engine is selected (at default)
    mailmotor.not_implemented.subscriber.gateway:
        class: MailMotor\Bundle\MailMotorBundle\Component\Gateway\NotImplementedSubscriberGateway
