services:
    # factory
    mailmotor.factory:
        class: MailMotor\Bundle\MailMotorBundle\Factory\MailMotorFactory
        arguments:
            - "@service_container"
            - "%mailmotor.mail_engine%"

    # gateways
    mailmotor.subscriber:
        class: MailMotor\Bundle\MailMotorBundle\Component\Subscriber
        arguments:
            - "@=service('mailmotor.factory').getSubscriberGateway()"
            - "@event_dispatcher"

    # this is our fallback gateway when no mail-engine is selected (at default)
    mailmotor.not_implemented.subscriber.gateway:
        class: MailMotor\Bundle\MailMotorBundle\Component\Gateway\NotImplementedSubscriberGateway
